version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
